name: JinroCraft
version: 1.1.0
main: net.atlantis.jinrocraft.JinroCraft
api-version: 1.16

commands:
  role:
    description: role command
    usage: /<command>
    permission: JinroCraft.admin
    permission-message: You don't have <permission>
  game:
    description: game command
    usage: /<command>
    permission: JinroCraft.admin
    permission-message: You don't have <permission>
  status:
    description: role command
    usage: /<command>
  jc:
    description: jinro chat command
    usage: /<command> text
  co:
    description: co command
    usage: /<command>
  vote:
    description: vote command
    usage: /<command> PlayerName
permissions:
  JinroCraft.admin:
    description: Gives access to JinroCraft admin commands
    default: op